services:
  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: siadlp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sql
    ports:
      - "5432:5432"
    volumes:
      - siadlp_pgdata:/var/lib/postgresql/data

volumes:
  siadlp_pgdata:
