export enum MovementType {
  COMPRA_ENTRADA = 'COMPRA_ENTRADA',
  PRODUCCION_SALIDA = 'PRODUCCION_SALIDA',
  PRODUCCION_ENTRADA = 'PRODUCCION_ENTRADA',
  DESPACHO_SALIDA = 'DESPACHO_SALIDA',
  AJUSTE_POSITIVO = 'AJUSTE_POSITIVO',
  AJUSTE_NEGATIVO = 'AJUSTE_NEGATIVO',
}
