export enum OrderStatus {
  REGISTERED = 'REGISTERED',
  CONFIRMED = 'CONFIRMED',
  DISPATCHED = 'DISPATCHED',
  ON_ROUTE = 'ON_ROUTE',
  DELIVERED = 'DELIVERED',
  COLLECTED = 'COLLECTED',
  ISSUE = 'ISSUE',
  CANCELLED = 'CANCELLED',
}
